package lk.ijse.aad68.crop_management_system.ENUMS;

public enum Designation {
 MANAGER,
 SENIOR_ASSISTANT_MANAGER,
 ASSISTANT_MANAGER,
 ADMIN_AND_HR_STAFF,
 OFFICE_ASSISTANT,
 SENIOR_AGRONOMIST,
 AGRONOMIST,
 SOIL_SCIENTIST,
 SENIOR_TECHNICIAN,
 TECHNICIAN,
 SUPERVISOR,
 LABOR
}
